name: BACKEND
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    name: Back-End YML
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back-end

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}